export const POLICY_REASONS = [
  "NETWORK_MISMATCH",
  "ASSET_NOT_ALLOWED",
  "RECIPIENT_NOT_ALLOWED",
  "BUDGET_EXCEEDED",
  "ALLOWANCE_EXPIRED",
  "ALLOWANCE_REVOKED",
  "ALLOWANCE_NOT_FOUND",
  "ALLOWANCE_NOT_ACTIVE",
  "SIGNER_NOT_AUTHORIZED",
  "SCOPE_NOT_ALLOWED",
  "MALFORMED_CHALLENGE",
  "UNSUPPORTED_SCHEME",
  "FACILITATOR_REJECTED",
  "SETTLEMENT_UNKNOWN",
  "RECEIPT_MISMATCH",
  "RESOURCE_UNLOCK_FAILED",
  "DUPLICATE_ATTEMPT",
  "UNSUPPORTED_CALL",
  "CONFIGURATION_ERROR",
] as const;

export type PolicyReason = (typeof POLICY_REASONS)[number];

export const REASON_MESSAGES: Record<PolicyReason, string> = {
  NETWORK_MISMATCH: "The payment network does not match the allowance.",
  ASSET_NOT_ALLOWED: "The payment asset is outside the allowance scope.",
  RECIPIENT_NOT_ALLOWED: "The payment recipient is not approved.",
  BUDGET_EXCEEDED: "The payment exceeds the remaining rolling budget.",
  ALLOWANCE_EXPIRED: "The allowance has expired.",
  ALLOWANCE_REVOKED: "The allowance rule has been revoked.",
  ALLOWANCE_NOT_FOUND: "The allowance could not be found.",
  ALLOWANCE_NOT_ACTIVE: "The allowance is not active.",
  SIGNER_NOT_AUTHORIZED: "The signer is not authorized by this allowance.",
  SCOPE_NOT_ALLOWED: "The contract invocation is outside the allowance scope.",
  MALFORMED_CHALLENGE: "The x402 challenge is malformed.",
  UNSUPPORTED_SCHEME: "The payment scheme is not supported.",
  FACILITATOR_REJECTED: "The facilitator rejected the payment authorization.",
  SETTLEMENT_UNKNOWN: "Settlement may have been submitted and must be reconciled.",
  RECEIPT_MISMATCH: "The settlement receipt does not match the challenge.",
  RESOURCE_UNLOCK_FAILED: "Payment settled but the protected resource did not unlock.",
  DUPLICATE_ATTEMPT: "This request already has a payment attempt.",
  UNSUPPORTED_CALL: "The smart-account invocation shape is unsupported.",
  CONFIGURATION_ERROR: "AgentAllowance configuration is invalid.",
};
